// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// InboundForm renders the create/edit form for one inbound. The
// `Transport` dropdown chooses between Telemost (current behaviour)
// and WB Stream (new transport, wired up in the parallel
// feat/sfu-multi-transport branch — UI is in place even though the
// backend won't honour it yet, by design of this branch).
func InboundForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"flex flex-col gap-3\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("{ transport: 'telemost' }")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/admin/ui/pages/inbound_form.templ`, Line: 11, Col: 38}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-post=\"/api/inbounds\" hx-ext=\"json-enc\" hx-on::after-request=\"if (event.detail.successful) { $store.modals.inbound = false; htmx.ajax('GET', '/htmx/inbounds', '#inbound-card-list'); }\"><div><label class=\"field-label\">Tag (короткое имя)</label> <input class=\"field-input\" name=\"tag\" placeholder=\"personal\"></div><div><label class=\"field-label\">Transport</label> <select class=\"field-input\" name=\"transport\" x-model=\"transport\"><option value=\"telemost\">Telemost</option> <option value=\"wb_stream\">WB Stream</option></select></div><div x-show=\"transport === 'telemost'\"><label class=\"field-label\">Meeting URL</label> <input class=\"field-input\" name=\"meeting\" placeholder=\"https://telemost.yandex.ru/j/...\"></div><div x-show=\"transport === 'wb_stream'\" x-cloak><label class=\"field-label\">Room URL</label> <input class=\"field-input\" name=\"meeting\" placeholder=\"https://stream.wb.ru/r/...\"> <button type=\"button\" class=\"btn-ghost mt-2 text-xs\" disabled title=\"Будет включено после мерджа feat/sfu-multi-transport\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("🔐 Authenticate via WB")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/admin/ui/pages/inbound_form.templ`, Line: 50, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</button></div><div><label class=\"field-label\">Display name (пусто = случайное)</label> <input class=\"field-input\" name=\"display_name\"></div><div x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("{ auto: true }")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/admin/ui/pages/inbound_form.templ`, Line: 60, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><label class=\"inline-flex items-center gap-2 text-sm\"><input type=\"checkbox\" name=\"auto_provision\" x-model=\"auto\" checked> <span>Создать новый WG-интерфейс автоматически</span></label><div class=\"mt-2\" x-show=\"!auto\" x-cloak><label class=\"field-label\">WG endpoint (если без авто-провижна)</label> <input class=\"field-input\" name=\"wg_endpoint\" value=\"127.0.0.1:51820\"></div></div><div class=\"flex gap-2 mt-1\"><button class=\"btn-primary\" type=\"submit\">Создать</button> <button class=\"btn-ghost\" type=\"button\" @click=\"$store.modals.inbound = false\">Отмена</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
